services:
  backend:
    build:
      context: ./backend
    container_name: banking_backend
    ports:
      - "8000:8000"
    environment:
      - APP_MODE=DEV
      - USE_MOCK_LLM=True
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rag_db
      - POSTGRES_HOST=db
    volumes:
      - ./backend/app:/app/app
    depends_on:
      - db
    networks:
      - banking-net

  frontend:
    image: node:20-alpine
    container_name: banking_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true # Recommended for hot reload in Docker on some systems
    networks:
      - banking-net
    depends_on:
      - backend

  db:
    image: pgvector/pgvector:pg16
    container_name: banking_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rag_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - banking-net

networks:
  banking-net:
    driver: bridge

volumes:
  postgres_data:
